-- Create user_profiles table
CREATE TABLE IF NOT EXISTS `user_profiles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `state` varchar(100) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `postal_code` varchar(20) DEFAULT NULL,
  `bio` text DEFAULT NULL,
  `profile_picture` varchar(255) DEFAULT NULL,
  `cover_photo` varchar(255) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  `job_title` varchar(255) DEFAULT NULL,
  `current_position` varchar(255) DEFAULT NULL,
  `industry` varchar(255) DEFAULT NULL,
  `years_of_experience` int DEFAULT NULL,
  `skills` text DEFAULT NULL,
  `highest_degree` varchar(100) DEFAULT NULL,
  `field_of_study` varchar(255) DEFAULT NULL,
  `institution` varchar(255) DEFAULT NULL,
  `year_of_graduation` year DEFAULT NULL,
  `additional_certifications` text DEFAULT NULL,
  `areas_of_interest` text DEFAULT NULL,
  `id_proof_path` varchar(255) DEFAULT NULL,
  `degree_certificates_path` text DEFAULT NULL,
  `cv_path` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `twitter` varchar(255) DEFAULT NULL,
  `linkedin` varchar(255) DEFAULT NULL,
  `github` varchar(255) DEFAULT NULL,
  `facebook` varchar(255) DEFAULT NULL,
  `instagram` varchar(255) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `nationality` varchar(100) DEFAULT NULL,
  `id_number` varchar(100) DEFAULT NULL,
  `passport_number` varchar(100) DEFAULT NULL,
  `membership_number` varchar(50) DEFAULT NULL,
  `membership_type` varchar(50) DEFAULT NULL,
  `membership_status` varchar(20) DEFAULT NULL,
  `membership_expiry` date DEFAULT NULL,
  `join_date` date DEFAULT NULL,
  `personal_info` text DEFAULT NULL,
  `contact_info` text DEFAULT NULL,
  `education` text DEFAULT NULL,
  `employment` text DEFAULT NULL,
  `membership_info` text DEFAULT NULL,
  `professional_certifications` text DEFAULT NULL,
  `linkedin_profile` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_id` (`user_id`),
  KEY `idx_membership_number` (`membership_number`),
  KEY `idx_membership_status` (`membership_status`)
  -- CONSTRAINT `fk_user_profiles_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
